// FIREBASE EXAMPLE CREATE DATA

// const tb_aturan = [
//   { ID: "1", kode_penyakit: "P01", kode_gejala: "G01", nilai: "0.2" },
//   { ID: "2", kode_penyakit: "P02", kode_gejala: "G01", nilai: "0.7" },
//   { ID: "3", kode_penyakit: "P03", kode_gejala: "G01", nilai: "0.7" },
//   { ID: "4", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "5", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "6", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "7", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "8", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "9", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "10", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "11", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },
//   { ID: "12", kode_penyakit: "P04", kode_gejala: "G01", nilai: "0.6" },

//   { ID: "5", kode_penyakit: "P01", kode_gejala: "G02", nilai: "0.9" },
//   { ID: "6", kode_penyakit: "P02", kode_gejala: "G02", nilai: "0.1" },
//   { ID: "7", kode_penyakit: "P03", kode_gejala: "G02", nilai: "0.2" },
//   { ID: "8", kode_penyakit: "P04", kode_gejala: "G02", nilai: "0.5" },
//   { ID: "9", kode_penyakit: "P01", kode_gejala: "G03", nilai: "0.2" },
//   { ID: "10", kode_penyakit: "P02", kode_gejala: "G03", nilai: "0.7" },
//   { ID: "11", kode_penyakit: "P03", kode_gejala: "G03", nilai: "0.2" },
//   { ID: "12", kode_penyakit: "P04", kode_gejala: "G03", nilai: "0.75" },
//   { ID: "13", kode_penyakit: "P01", kode_gejala: "G04", nilai: "0.2" },
//   { ID: "14", kode_penyakit: "P02", kode_gejala: "G04", nilai: "0.9" },
//   { ID: "15", kode_penyakit: "P03", kode_gejala: "G04", nilai: "0.2" },
//   { ID: "16", kode_penyakit: "P04", kode_gejala: "G04", nilai: "0.2" },
//   { ID: "17", kode_penyakit: "P01", kode_gejala: "G05", nilai: "0.2" },
//   { ID: "18", kode_penyakit: "P02", kode_gejala: "G05", nilai: "0.3" },
//   { ID: "19", kode_penyakit: "P03", kode_gejala: "G05", nilai: "0.2" },
//   { ID: "20", kode_penyakit: "P04", kode_gejala: "G05", nilai: "0.9" },
//   { ID: "21", kode_penyakit: "P01", kode_gejala: "G06", nilai: "0.95" },
//   { ID: "22", kode_penyakit: "P02", kode_gejala: "G06", nilai: "0.3" },
//   { ID: "23", kode_penyakit: "P03", kode_gejala: "G06", nilai: "0.7" },
//   { ID: "24", kode_penyakit: "P04", kode_gejala: "G06", nilai: "0.3" },
//   { ID: "25", kode_penyakit: "P01", kode_gejala: "G07", nilai: "0.2" },
// ];

const tbAturan = [
  {
    ID: 1,
    kode_penyakit: "P01",
    kode_gejala: "G01",
    nilai: "0.7",
  },
  {
    ID: 2,
    kode_penyakit: "P02",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 3,
    kode_penyakit: "P03",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 4,
    kode_penyakit: "P04",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 5,
    kode_penyakit: "P05",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 6,
    kode_penyakit: "P06",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 7,
    kode_penyakit: "P07",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 8,
    kode_penyakit: "P08",
    kode_gejala: "G01",
    nilai: "0.2",
  },
  {
    ID: 9,
    kode_penyakit: "P01",
    kode_gejala: "G02",
    nilai: "0.6",
  },
  {
    ID: 10,
    kode_penyakit: "P02",
    kode_gejala: "G02",
    nilai: "0.2",
  },
  {
    ID: 11,
    kode_penyakit: "P03",
    kode_gejala: "G02",
    nilai: "0.2",
  },
  {
    ID: 12,
    kode_penyakit: "P04",
    kode_gejala: "G02",
    nilai: "0.2",
  },
  {
    ID: 13,
    kode_penyakit: "P05",
    kode_gejala: "G02",
    nilai: "0.5",
  },
  {
    ID: 14,
    kode_penyakit: "P06",
    kode_gejala: "G02",
    nilai: "0.2",
  },
  {
    ID: 15,
    kode_penyakit: "P07",
    kode_gejala: "G02",
    nilai: "0.2",
  },
  {
    ID: 16,
    kode_penyakit: "P08",
    kode_gejala: "G02",
    nilai: "0.7",
  },
  {
    ID: 17,
    kode_penyakit: "P01",
    kode_gejala: "G03",
    nilai: "0.8",
  },
  {
    ID: 18,
    kode_penyakit: "P02",
    kode_gejala: "G03",
    nilai: "0.2",
  },
  {
    ID: 19,
    kode_penyakit: "P03",
    kode_gejala: "G03",
    nilai: "0.2",
  },
  {
    ID: 20,
    kode_penyakit: "P04",
    kode_gejala: "G03",
    nilai: "0.2",
  },
  {
    ID: 21,
    kode_penyakit: "P05",
    kode_gejala: "G03",
    nilai: "0.2",
  },
  {
    ID: 22,
    kode_penyakit: "P06",
    kode_gejala: "G03",
    nilai: "0.2",
  },
  {
    ID: 23,
    kode_penyakit: "P07",
    kode_gejala: "G03",
    nilai: "0.2",
  },
  {
    ID: 24,
    kode_penyakit: "P08",
    kode_gejala: "G03",
    nilai: "0.7",
  },
  {
    ID: 25,
    kode_penyakit: "P01",
    kode_gejala: "G04",
    nilai: "0.2",
  },
  {
    ID: 26,
    kode_penyakit: "P02",
    kode_gejala: "G04",
    nilai: "0.7",
  },
  {
    ID: 27,
    kode_penyakit: "P03",
    kode_gejala: "G04",
    nilai: "0.6",
  },
  {
    ID: 28,
    kode_penyakit: "P04",
    kode_gejala: "G04",
    nilai: "0.2",
  },
  {
    ID: 29,
    kode_penyakit: "P05",
    kode_gejala: "G04",
    nilai: "0.2",
  },
  {
    ID: 30,
    kode_penyakit: "P06",
    kode_gejala: "G04",
    nilai: "0.2",
  },
  {
    ID: 31,
    kode_penyakit: "P07",
    kode_gejala: "G04",
    nilai: "0.2",
  },
  {
    ID: 32,
    kode_penyakit: "P08",
    kode_gejala: "G04",
    nilai: "0.2",
  },
  {
    ID: 33,
    kode_penyakit: "P01",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 34,
    kode_penyakit: "P02",
    kode_gejala: "G05",
    nilai: "0.6",
  },
  {
    ID: 35,
    kode_penyakit: "P03",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 36,
    kode_penyakit: "P04",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 37,
    kode_penyakit: "P05",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 38,
    kode_penyakit: "P06",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 39,
    kode_penyakit: "P07",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 40,
    kode_penyakit: "P08",
    kode_gejala: "G05",
    nilai: "0.2",
  },
  {
    ID: 41,
    kode_penyakit: "P01",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 42,
    kode_penyakit: "P02",
    kode_gejala: "G06",
    nilai: "0.7",
  },
  {
    ID: 43,
    kode_penyakit: "P03",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 44,
    kode_penyakit: "P04",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 45,
    kode_penyakit: "P05",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 46,
    kode_penyakit: "P06",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 47,
    kode_penyakit: "P07",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 48,
    kode_penyakit: "P08",
    kode_gejala: "G06",
    nilai: "0.2",
  },
  {
    ID: 49,
    kode_penyakit: "P01",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 50,
    kode_penyakit: "P02",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 51,
    kode_penyakit: "P03",
    kode_gejala: "G07",
    nilai: "0.9",
  },
  {
    ID: 52,
    kode_penyakit: "P04",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 53,
    kode_penyakit: "P05",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 54,
    kode_penyakit: "P06",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 55,
    kode_penyakit: "P07",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 56,
    kode_penyakit: "P08",
    kode_gejala: "G07",
    nilai: "0.2",
  },
  {
    ID: 57,
    kode_penyakit: "P01",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 58,
    kode_penyakit: "P02",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 59,
    kode_penyakit: "P03",
    kode_gejala: "G08",
    nilai: "0.7",
  },
  {
    ID: 60,
    kode_penyakit: "P04",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 61,
    kode_penyakit: "P05",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 62,
    kode_penyakit: "P06",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 63,
    kode_penyakit: "P07",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 64,
    kode_penyakit: "P08",
    kode_gejala: "G08",
    nilai: "0.2",
  },
  {
    ID: 65,
    kode_penyakit: "P01",
    kode_gejala: "G09",
    nilai: "0.2",
  },
  {
    ID: 66,
    kode_penyakit: "P02",
    kode_gejala: "G09",
    nilai: "0.2",
  },
  {
    ID: 67,
    kode_penyakit: "P03",
    kode_gejala: "G09",
    nilai: "0.6",
  },
  {
    ID: 68,
    kode_penyakit: "P04",
    kode_gejala: "G09",
    nilai: "0.2",
  },
  {
    ID: 69,
    kode_penyakit: "P05",
    kode_gejala: "G09",
    nilai: "0.2",
  },
  {
    ID: 70,
    kode_penyakit: "P06",
    kode_gejala: "G09",
    nilai: "0.2",
  },
  {
    ID: 71,
    kode_penyakit: "P07",
    kode_gejala: "G09",
    nilai: "0.7",
  },
  {
    ID: 72,
    kode_penyakit: "P08",
    kode_gejala: "G09",
    nilai: "0.2",
  },
  {
    ID: 73,
    kode_penyakit: "P01",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 74,
    kode_penyakit: "P02",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 75,
    kode_penyakit: "P03",
    kode_gejala: "G10",
    nilai: "0.8",
  },
  {
    ID: 76,
    kode_penyakit: "P04",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 77,
    kode_penyakit: "P05",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 78,
    kode_penyakit: "P06",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 79,
    kode_penyakit: "P07",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 80,
    kode_penyakit: "P08",
    kode_gejala: "G10",
    nilai: "0.2",
  },
  {
    ID: 81,
    kode_penyakit: "P01",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 82,
    kode_penyakit: "P02",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 83,
    kode_penyakit: "P03",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 84,
    kode_penyakit: "P04",
    kode_gejala: "G11",
    nilai: "0.7",
  },
  {
    ID: 85,
    kode_penyakit: "P05",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 86,
    kode_penyakit: "P06",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 87,
    kode_penyakit: "P07",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 88,
    kode_penyakit: "P08",
    kode_gejala: "G11",
    nilai: "0.2",
  },
  {
    ID: 89,
    kode_penyakit: "P01",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 90,
    kode_penyakit: "P02",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 91,
    kode_penyakit: "P03",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 92,
    kode_penyakit: "P04",
    kode_gejala: "G12",
    nilai: "0.8",
  },
  {
    ID: 93,
    kode_penyakit: "P05",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 94,
    kode_penyakit: "P06",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 95,
    kode_penyakit: "P07",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 96,
    kode_penyakit: "P08",
    kode_gejala: "G12",
    nilai: "0.2",
  },
  {
    ID: 97,
    kode_penyakit: "P01",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 98,
    kode_penyakit: "P02",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 99,
    kode_penyakit: "P03",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 100,
    kode_penyakit: "P04",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 101,
    kode_penyakit: "P05",
    kode_gejala: "G13",
    nilai: "0.9",
  },
  {
    ID: 102,
    kode_penyakit: "P06",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 103,
    kode_penyakit: "P07",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 104,
    kode_penyakit: "P08",
    kode_gejala: "G13",
    nilai: "0.2",
  },
  {
    ID: 105,
    kode_penyakit: "P01",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 106,
    kode_penyakit: "P02",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 107,
    kode_penyakit: "P03",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 108,
    kode_penyakit: "P04",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 109,
    kode_penyakit: "P05",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 110,
    kode_penyakit: "P06",
    kode_gejala: "G14",
    nilai: "0.8",
  },
  {
    ID: 111,
    kode_penyakit: "P07",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 112,
    kode_penyakit: "P08",
    kode_gejala: "G14",
    nilai: "0.2",
  },
  {
    ID: 113,
    kode_penyakit: "P01",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 114,
    kode_penyakit: "P02",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 115,
    kode_penyakit: "P03",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 116,
    kode_penyakit: "P04",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 117,
    kode_penyakit: "P05",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 118,
    kode_penyakit: "P06",
    kode_gejala: "G15",
    nilai: "0.9",
  },
  {
    ID: 119,
    kode_penyakit: "P07",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 120,
    kode_penyakit: "P08",
    kode_gejala: "G15",
    nilai: "0.2",
  },
  {
    ID: 121,
    kode_penyakit: "P01",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 122,
    kode_penyakit: "P02",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 123,
    kode_penyakit: "P03",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 124,
    kode_penyakit: "P04",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 125,
    kode_penyakit: "P05",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 126,
    kode_penyakit: "P06",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 127,
    kode_penyakit: "P07",
    kode_gejala: "G16",
    nilai: "0.8",
  },
  {
    ID: 128,
    kode_penyakit: "P08",
    kode_gejala: "G16",
    nilai: "0.2",
  },
  {
    ID: 129,
    kode_penyakit: "P01",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 130,
    kode_penyakit: "P02",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 131,
    kode_penyakit: "P03",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 132,
    kode_penyakit: "P04",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 133,
    kode_penyakit: "P05",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 134,
    kode_penyakit: "P06",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 135,
    kode_penyakit: "P07",
    kode_gejala: "G17",
    nilai: "0.9",
  },
  {
    ID: 136,
    kode_penyakit: "P08",
    kode_gejala: "G17",
    nilai: "0.2",
  },
  {
    ID: 137,
    kode_penyakit: "P01",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 138,
    kode_penyakit: "P02",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 139,
    kode_penyakit: "P03",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 140,
    kode_penyakit: "P04",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 141,
    kode_penyakit: "P05",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 142,
    kode_penyakit: "P06",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 143,
    kode_penyakit: "P07",
    kode_gejala: "G18",
    nilai: "0.2",
  },
  {
    ID: 144,
    kode_penyakit: "P08",
    kode_gejala: "G18",
    nilai: "0.9",
  },
];

// async function create() {
//   tb_aturan.map(async (item) => {
//     await setDoc(doc(db, "rules", item.ID), {
//       code_problem: item.kode_penyakit,
//       code_indication: item.kode_gejala,
//       value: item.nilai,
//     }).then(() => console.log(`success ${item.ID}`));
//   });
// }

// create();

module.exports = { tbAturan };
